id: P006862
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W22181
  title: སྟོན་པའི་རྣམ་ཐར་ཆེན་མོ
  author: ''
  volumes:
    bbe523326c7c49179b0a3df999a4470b:
      image_group_id: I1PD36395
      title: ''
      volume_number: 1
      total_pages: 534
      base_file: v001.txt
